### ISSUE TITLE
git clone --recursive can't clone submodules

### ISSUE THREAD

**Issue by 2channelkrt** [planetarium/NineChronicles.Standalone#184]
error occurs as:

git@github.com: Permission denied (publickey)

**Comment by riemannulus** [comment]
Thanks for reporting!

What is your way to cloning the repository? `ssh` or `http/s`?

**Comment by 2channelkrt** [comment]
https

**Comment by riemannulus** [comment]
Unfortunately, the submodule clone is not supported under `HTTP/S`. Could you try clone with `SSH`?

**Comment by 2channelkrt** [comment]
i created ssh key to my virtualbox environment and added public key to my github account. After executing

![image](https://user-images.githubusercontent.com/38805468/99965341-14cb8480-2dd8-11eb-95e6-d9274dda679b.png)

Sorry, I'm total newbie here...

**Comment by 2channelkrt** [comment]
oops, nevermind. Rebooted the system and seems to be working here.

**Comment by riemannulus** [comment]
Ok, close this issue.
